### PR TITLE
Added port checking bailout in quasar-dev and fixed typos in spawn.

### PR DESCRIPTION
**Pull request by smolinari**
Hope it is ok!

Scott

### CODE REVIEW

**Comment by rstoenescu** [comment]
We still need to test this out on all platforms (Win, Linux, MacOS) before I launch the new CLI version.

**Comment by smolinari** [comment]
With Win 10 Pro it works. 😄 I can set up a Linux container and test that too. I also have a bit older Mac Book Pro, but have never done any development work on it. Shouldn't be too much of a problem to run through some tests on it though. 

Scott

**Comment by rstoenescu** [comment]
No, I take care of Linux. I'm running on Linux. Wait a little, want to make some small tweaks. Don't test yet pls. Thanks for this PR!

**Comment by rstoenescu** [comment]
Done. Can you test on Windows with "dev" branch? On the CLI repo, switch to "dev" branch then "npm link". You'll have the global Quasar CLI linked to this folder so you can test easily.

**Comment by smolinari** [comment]
Works! I also see what you changed. Learning. 😉 

Scott

**Pull request merged**
