### PR TITLE
Fix #93 and #95 : Added afterBuild step

### LINKED ISSUE #93: [Bug] Custom Webpack Plugins are run BEFORE Electron build is complete
### Software version

OS: Debian 9
Node: v8.9.4
NPM: 5.7.1
Quasar CLI: v0.15.9

### What did you get as the error?

When Webpack runs the Custom Plugins added in 

```
electron: {
  extendWebpack (cfg) {
    // <<<--- CUSTOM PLUGINS ADDED HERE --- >>>
  }
}
```
are run before the Electron build is complete. The `\electron-mat` folder contains only the `Unpackaged` folder and not yet, for example, the bundled linux folder.

This is causing us troubles into upgrading to Quasar v0.15, because in v0.14 we could customize our builds my editing the scripts files of the `/build` folder.

### What were you expecting?

I would expect the custom Webpack Plugins to be run **after** the complete build process, otherwise it is not possible to perform operations on the builds, such as zip them.

### What steps did you take, to get the error?

Just add a custom plugin, for example a Webpack Zip Plugin, and try to zip the Electron build. The problem is that it doesn't exist.

### Proposed solutions

A simple solution would be to allow some custom code to run after the Electron build is complete. A new Issue will soon be opened to propose this new feature.

### PR DESCRIPTION
**Pull request by ExNG**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [x] Other, please describe: Build related new feature

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch and _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on Windows
- [x] It's been tested on Linux
- [ ] It's been tested on MacOS
- [x] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar-framework.org/tree/master/source) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.
  **The documentation is in the quasar-framework.org repo**, a PR will shortly follow.

If adding a **new feature**, the PR's description includes:
- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
It exactly implements the proposed feature in #95 .

### CODE REVIEW

**Comment by ExNG** [comment]
Created PR to add documentation update in the quasar-framework.org repo: https://github.com/quasarframework/quasar-framework.org/pull/425 .

**Comment by micheleangioni** [comment]
Hi @rstoenescu , 
could you please provide an update on this PR, #93 and #95 ?
We would need to know if the merging of this PR is under evaluation or other solutions are being considered, in order to complete our upgrade process to v0.15.

Thanks for you invaluable work.

**Comment by micheleangioni** [comment]
Thank you very much :)

**Comment by rstoenescu** [comment]
Pushed commit which adds quasar.conf > electron.beforePackaging()
** Available in next release: 0.15.13**

Examples:

```js
electron: {
  beforePackaging ({ appPaths, unpackagedDir }) {
    // do something...
  }
}
```
```js
electron: {
  beforePackaging ({ appPaths, unpackagedDir }) {
    return new Promise((resolve, reject) => {
      .... resolve() ...
    })
  })
}
```

Please note that the Electron build is a three step process. First step is to bundle the renderer process. Second is to bundle the main process. Finally, last step is to use Electron Packager to package the app into an executable.
`beforePackaging` is executed between step 2 and step 3.

Anything after step 3 can easily be executed after Quasar CLI finishes its job.

**Comment by micheleangioni** [comment]
Ok thanks @rstoenescu , great job!
Honestly, even though it's easy to do in a separated script, it would be great to have also a `afterPackaging` option. This would remove the need of an external script and let Quasar to keep everything in one place (the quasar.conf file).

**Comment by micheleangioni** [comment]
Ok, I understand :)

**Pull request closed without merging**
