### PR TITLE
Hot fix for web workers to build with global reference

### PR DESCRIPTION
**Pull request by disarticulate**
https://github.com/webpack/webpack/issues/6642
https://github.com/Microsoft/monaco-editor/issues/768

**What kind of change does this PR introduce?** (check at least one)

- [x ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [ ] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested on Windows
- [ ] It's been tested on Linux
- [ ] It's been tested on MacOS
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar-framework.org/tree/master/source) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by rstoenescu** [comment]
Hi,

Quasar allows devs to extend the default Webpack config to make it work with web workers:

```js
// quasar.conf.js

build: {
  extendWebpack (cfg) {
    cfg.output.globalObject = 'this'
  }
}
```

I feel like this is something that can brake PWA for example. Since it's specific to web workers only, it's better to leave this out for devs to extend the default config on a need to have basis.

Thank you for taking time for a PR, though!

**Comment by disarticulate** [comment]
Note: this only fixed building. HMR is still broken in 0.16.3

**Comment by rstoenescu** [comment]
1. How should the webpack config be altered for making HMR work too?
2. You should instead push for this to be fixed in Webpack rather than looking for Quasar to patch Webpack bugs.

**Comment by disarticulate** [comment]
When I looked at the issues, it looked like it had something to do with a new webpack. I'm probably wrong as i'm looking at quasar-cli package.json and webpack is at 4.9.1 in both. let me look further, I thought i saw the issue in a few places.

**Comment by disarticulate** [comment]
this is the issue that seems to document the behavior:

https://github.com/webpack/webpack/issues/6642

Which references 4.0.1. I'm so confused.

It does look like 0.15 -> 0.16 upgraded

https://github.com/quasarframework/quasar-cli/commit/c64234f642f4f221ff113f7a5f533e7b099bdc7a#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

**Comment by disarticulate** [comment]
note, Quasar-cli 0.15.20 will install quasar-cli 0.16.0 which is confusing me.

**Comment by disarticulate** [comment]
https://github.com/webpack/webpack/issues/6525

**Pull request closed without merging**
