### PR TITLE
feat: Allow multiple files to be created with the 'quasar new' at once

### PR DESCRIPTION
**Pull request by lmfresneda**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] It's been tested on Windows
- [ ] It's been tested on Linux
- [ ] It's been tested on MacOS
- [x] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar-framework.org/tree/master/source) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

* These changes allow multiple files to be created with the 'quasar new' command at the same time, for example:

```shell
$ quasar new layout Hello World
```

* If this PR is merged, de doc in http://quasar-framework.org/guide/quasar-cli.html should be updated, but I don't know if it should be done before or after

### CODE REVIEW

**Comment by rstoenescu** [comment]
Thanks for taking time for the PR!

**Comment by rstoenescu** [comment]
Just want to confirm. This was for the old CLI and not the new one (which is on "next" branch).

**Comment by lmfresneda** [comment]
Sorry, it's for old CLI. Thanks!

**Comment by rstoenescu** [comment]
Will make a release for the old CLI to include this in 1-2 days max.

**Comment by rstoenescu** [comment]
Released CLI v0.6.5 which contains this change. Thanks again for contributing!

**Comment by lmfresneda** [comment]
Perfect! your welcome!

**Pull request merged**
